/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: RenderX (https://sketchfab.com/RenderX)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/moon-26cc0b7878bb4d919b68e2be399db466
Title: moon
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

// Smart asset URL resolver - uses assets for dev, public for production
const getAssetUrl = (path) => {
  if (import.meta.env.DEV) {
    // Development: use assets directory
    return path.startsWith('/') ? path.substring(1) : path;
  } else {
    // Production: use public directory
    return path.startsWith('/') ? path : `/${path}`;
  }
};

export default function MoonGLTF({ url = getAssetUrl('moon(2).glb'), isMobile = false, ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(url)
  useAnimations(animations, group)
  
  // Apply mobile scaling if needed
  const mobileProps = isMobile ? { scale: 0.8 } : {};
  
  return (
    <group ref={group} {...mobileProps} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="b964401c34154430bb1a8d7a5fa66a66fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Sphere" rotation={[-1.264, 0.489, 0.961]} scale={100}>
                  <mesh
                    name="Sphere_Material001_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Sphere_Material001_0.geometry}
                    material={materials['Material.001']}
                  />
                  <mesh
                    name="Sphere_Material001_0_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Sphere_Material001_0_1.geometry}
                    material={materials['Material.001']}
                  />
                  <mesh
                    name="Sphere_Material001_0_2"
                    castShadow
                    receiveShadow
                    geometry={nodes.Sphere_Material001_0_2.geometry}
                    material={materials['Material.001']}
                  />
                  <mesh
                    name="Sphere_Material001_0_3"
                    castShadow
                    receiveShadow
                    geometry={nodes.Sphere_Material001_0_3.geometry}
                    material={materials['Material.001']}
                  />
                  <mesh
                    name="Sphere_Material001_0_4"
                    castShadow
                    receiveShadow
                    geometry={nodes.Sphere_Material001_0_4.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Camera"
                  position={[528.602, 195.596, -369.365]}
                  rotation={[3.125, -0.606, 2.837]}
                  scale={100}>
                  <group name="Object_11" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
} 